# Generated by Django 4.2.4 on 2023-08-13 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookid', models.IntegerField()),
                ('bookname', models.CharField(max_length=10)),
                ('book_author', models.CharField(max_length=50)),
            ],
        ),
    ]
