# Generated by Django 4.2.4 on 2023-08-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentlibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_rollnumber', models.IntegerField()),
                ('bookid', models.IntegerField()),
                ('issue_date', models.DateField()),
                ('return_date', models.DateField()),
                ('time_period', models.DateField()),
                ('penalty', models.IntegerField()),
            ],
        ),
    ]
