# Generated by Django 4.2.4 on 2023-08-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentlibrary', '0002_alter_studentlibrary_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentlibrary',
            name='penalty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentlibrary',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
